name: Integration tests

on:  
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Setup backend server in docker container
      run: |
        docker build . --file Dockerfile --tag img-app:latest
        docker run -p 6000:6000 -d --name app img-app:latest
    - name: Install pytest
      run: |
        conda install pytest
    - name: Run integration tests
      run: |
        python -m pytest -k "test_api"